"""
Discovers individual transcript URLs from a source's index/listing pages
and writes them into raw_inputs/<source>/links/urls.txt for scraper.py
to pick up. scraper.py itself does NOT crawl -- it only ever visits
exactly what's in urls.txt. This is the tool that builds that list.

Run:
    python discover_links.py quo
    python discover_links.py michael

NOTE ON TESTING: I (the assistant) cannot make live network calls from
the sandbox this was written in, so this hasn't been run against the
real sites end-to-end. The URL pattern matching was built from real pages
I fetched and inspected, but pagination behavior in particular is my
best guess from the site structure, not something I watched run. Expect
to need a tweak or two on the first real run -- if it grabs zero links
or way too many, paste me the printed output and I'll adjust the regex.
"""

import argparse
import re
import sys
import time

import requests
from bs4 import BeautifulSoup

from parsers.michael import _parse_date_from_slug

REQUEST_DELAY_SECONDS = 1.0  # be polite -- these are small non-profit/hobby sites
MAX_PAGES_SAFETY_CAP = 80    # stop crawling even if pagination looks infinite


def _fetch_soup(url: str) -> BeautifulSoup:
    headers = {"User-Agent": "Mozilla/5.0 (Project Prism research scraper)"}
    response = requests.get(url, headers=headers, timeout=20)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


def _write_urls(source_key: str, urls: list):
    import os
    folder = os.path.join("raw_inputs", source_key, "links")
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, "urls.txt")

    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            existing = {line.strip() for line in f if line.strip() and not line.startswith("#")}

    combined = sorted(existing | set(urls))
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# Auto-generated by discover_links.py -- {len(combined)} URLs\n")
        for url in combined:
            f.write(url + "\n")

    new_count = len(set(urls) - existing)
    print(f"\n[{source_key.upper()}] {path}: {len(combined)} total URLs "
          f"({new_count} newly discovered this run)")


# ---------------------------------------------------------------------
# Q'uo / Hatonn / Latwii (llresearch.org conscious channeling archive)
# ---------------------------------------------------------------------
# Session links look like /channeling/2026/0517 or /channeling/2026/0317_01
# (exactly 4 digits, optionally with a _NN suffix for same-day multi-part
# sessions). Pagination links for a given year look like /channeling/2026/1,
# /channeling/2026/2 -- a bare 1-2 digit page index, NOT a 4-digit date.
# That digit-count difference is how we tell them apart.

SESSION_LINK_RE = re.compile(r'/channeling/(\d{4})/(\d{4}(?:_\d{2})?)$')
PAGE_LINK_RE = re.compile(r'/channeling/(\d{4})/(\d{1,2})$')


def discover_quo_links(start_year: int = 1972, end_year: int = 2026):
    base = "https://www.llresearch.org"
    all_session_urls = set()

    for year in range(start_year, end_year + 1):
        page = 1
        while page <= MAX_PAGES_SAFETY_CAP:
            url = f"{base}/channeling/{year}/{page}"
            try:
                soup = _fetch_soup(url)
            except requests.RequestException as exc:
                print(f"  [{year} page {page}] fetch failed: {exc}")
                break

            found_session_link_this_page = False
            found_next_page_link = False

            for a in soup.find_all("a", href=True):
                href = a["href"]
                if SESSION_LINK_RE.search(href):
                    full_url = href if href.startswith("http") else base + href
                    if full_url not in all_session_urls:
                        all_session_urls.add(full_url)
                    found_session_link_this_page = True
                elif PAGE_LINK_RE.search(href):
                    match = PAGE_LINK_RE.search(href)
                    if int(match.group(1)) == year and int(match.group(2)) > page:
                        found_next_page_link = True

            print(f"  [{year} page {page}] {len(all_session_urls)} total session URLs so far")

            if not found_session_link_this_page and page > 1:
                break  # ran out of content for this year
            if not found_next_page_link:
                break  # no further pagination found

            page += 1
            time.sleep(REQUEST_DELAY_SECONDS)

        time.sleep(REQUEST_DELAY_SECONDS)

    return sorted(all_session_urls)


# ---------------------------------------------------------------------
# Michael Teachings
# ---------------------------------------------------------------------
# The transcripts index page lists hrefs directly -- no pagination
# observed on the main table-of-contents page itself. We filter to only
# links whose slug actually parses as a date (reusing the same logic
# michael.py uses), which conveniently excludes the non-transcript pages
# that live in the same folder (welcome.html, mfaq.html, etc.) without
# needing an explicit blocklist.

def discover_michael_links():
    url = "https://www.michaelteachings.com/michael-teachings-transcripts.html"
    soup = _fetch_soup(url)

    urls = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if "michael_teachings_transcripts/" not in href:
            continue
        slug = href.rstrip("/").split("/")[-1]
        if slug.lower().endswith(".html"):
            slug = slug[:-5]
        if _parse_date_from_slug(slug) is not None:
            full_url = href if href.startswith("http") else "https://www.michaelteachings.com" + href
            urls.append(full_url)

    print(f"  Found {len(urls)} date-parseable transcript links")
    return sorted(set(urls))


DISCOVERERS = {
    "quo": discover_quo_links,
    "michael": discover_michael_links,
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", choices=DISCOVERERS.keys())
    args = parser.parse_args()

    print(f"Discovering links for '{args.source}'...")
    urls = DISCOVERERS[args.source]()
    if not urls:
        print(f"\n[{args.source.upper()}] No URLs discovered. The site's HTML "
              f"structure may not match what this script expects -- paste me "
              f"the output and a sample page URL and I'll adjust the patterns.")
        sys.exit(1)
    _write_urls(args.source, urls)


if __name__ == "__main__":
    main()
